version: "3.9"
services:
  postgres:
    image: postgres:alpine
    env_file:
      - app.env
    ports:
      - "5432:5432"
    volumes:
      - ./db_data_volume:/var/lib/postgresql/data
    restart: always
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    entrypoint:
      [
        "/app/wait-for.sh",
        "postgres:5432",
        "--",
        "/app/start.sh"
      ]
    command: [ "/app/main" ]
# volumes:
#   data-volume:
