// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0
// source: users.sql

package db

import (
	"context"
	"database/sql"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (username, password, description, activated)
VALUES ($1, $2, $3, $4)
RETURNING uid, username, password, description, activated
`

type CreateUserParams struct {
	Username    string         `json:"username"`
	Password    string         `json:"password"`
	Description sql.NullString `json:"description"`
	Activated   bool           `json:"activated"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.Username,
		arg.Password,
		arg.Description,
		arg.Activated,
	)
	var i User
	err := row.Scan(
		&i.Uid,
		&i.Username,
		&i.Password,
		&i.Description,
		&i.Activated,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT uid, username, password, description, activated
FROM users
WHERE username = $1
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.Uid,
		&i.Username,
		&i.Password,
		&i.Description,
		&i.Activated,
	)
	return i, err
}

const getUserByUsernameForUpdate = `-- name: GetUserByUsernameForUpdate :one
SELECT uid, username, password, description, activated
FROM users
WHERE username = $1
    FOR NO KEY UPDATE
`

func (q *Queries) GetUserByUsernameForUpdate(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByUsernameForUpdate, username)
	var i User
	err := row.Scan(
		&i.Uid,
		&i.Username,
		&i.Password,
		&i.Description,
		&i.Activated,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT uid, username, password, description, activated
FROM users
WHERE activated = TRUE
ORDER BY uid
LIMIT $1 OFFSET $2
`

type ListUsersParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, listUsers, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.Uid,
			&i.Username,
			&i.Password,
			&i.Description,
			&i.Activated,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET username  = $2,
    password  = $3,
    description = $4,
    activated = $5
WHERE uid = $1
RETURNING uid, username, password, description, activated
`

type UpdateUserParams struct {
	Uid         int32          `json:"uid"`
	Username    string         `json:"username"`
	Password    string         `json:"password"`
	Description sql.NullString `json:"description"`
	Activated   bool           `json:"activated"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, updateUser,
		arg.Uid,
		arg.Username,
		arg.Password,
		arg.Description,
		arg.Activated,
	)
	var i User
	err := row.Scan(
		&i.Uid,
		&i.Username,
		&i.Password,
		&i.Description,
		&i.Activated,
	)
	return i, err
}
